---
title: "Class08"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# K means clustering
# Generate some example data for clustering
tmp <- c(rnorm(30,-3), rnorm(30,3))
x <- cbind(x=tmp, y=rev(tmp))
plot(x)
```

```{r}
## Use the kmeans() function setting k to 2 and nstart=20 
k2 <- kmeans(x, centers=2, nstart=20)
k2
```

```{r}
# How many points in each cluster?
k2$size
table(k2$cluster)
# What is the cluster center?
k2$centers
# Plot X colored by kmeans cluster assignment
plot(x, col=k2$cluster)
points(k2$centers, col= "blue", pch = 18, cex = 3)
```



```{r}
# First we need to calculate point (dis)similarity
# as the Euclidean distance between observations
dist_matrix <- dist(x)
# The hclust() function returns a hierarchical
# clustering model
hc <- hclust(d = dist_matrix)
# the print method is not so useful here
hc
```

```{r}
plot(hc)
abline(h=6, col="red")
cutree(hc, h=6)
```


```{r}
gp2 <- cutree(hc, k=2)
gp2
```

```{r}
gp3 <- cutree(hc, k=3)
gp3
```

```{r}
table(gp3)
table(gp2)
table(gp2, gp3)
```

```{r}
x <- rbind(
 matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2), # c1
 matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
 matrix(c(rnorm(50, mean = 1, sd = 0.3), # c3
 rnorm(50, mean = 0, sd = 0.3)), ncol = 2))
colnames(x) <- c("x", "y")
# Step 2. Plot the data without clustering
plot(x)
# Step 3. Generate colors for known clusters
# (just so we can compare to hclust results)
col <- as.factor( rep(c("c1","c2","c3"), each=50) )
plot(x, col=col)
```


```{r}
# Use the dist(), hclust(), plot() and cutree() functions to return 2 and 3 clusters. How does this compare to your known 'col' groups?
dist_matrix <- dist(x)
# The hclust() function returns a hierarchical clustering model
hc <- hclust(d = dist_matrix)
plot(hc)
```
```{r}
val2 <- cutree(hc, k=2)
```
```{r}
val3 <- cutree(hc, k=3)
```
```{r}
table(val2, val3)
```
```{r}
plot(hc)
abline(h=1.5, col="red")
cutree(hc, h=1.5)
```
```{r}
plot(x, col=val2)
```

```{r}
plot(x, col=val3)
```

Moving on to Principal Component Analysis:
```{r}
mydata <- read.csv("https://tinyurl.com/expression-CSV", row.names = 1)
```
There are `r nrow(mydata)` genes in this dataset
Let's run PCA
```{r}
pca <- prcomp(t(mydata), scale=TRUE)
summary(pca)
attributes(pca)
```

The first PCA plot
```{r}
plot(x = pca$x[,1], y = pca$x[,2])
```
Let's get our scree plot
```{r}
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
barplot(pca.var.per)
```
```{r}
mycols <- c(rep("red", 5), rep("blue", 5))
```

A nicer PCA plot
```{r}
plot(x = pca$x[,1], y = pca$x[,2], xlab = paste("PC1 (",pca.var.per[1], "%)"), ylab = paste("PC2 (", pca.var.per[2], "%)"), col = mycols)
text(pca$x[,1], y = pca$x[,2], colnames(mydata))
```

```{r}
x <- read.csv("UK_foods.csv", row.names = 1)
dim(x)
nrow(x)
ncol(x)
x
```

```{r}
barplotx <- barplot(as.matrix(x), beside=F, col=rainbow(nrow(x)))
barplotx
pairanalysis <- pairs(x, col=rainbow(10), pch=16)
pairanalysis
```

```{r}
pca <- prcomp(t(x))
summary(pca)
```

```{r}
# Plot PC1 vs PC2
mycols <- c("orange", "red", "blue", "green")
plot(pca$x[,1], pca$x[,2], xlab="PC1", ylab="PC2", xlim=c(-270,500))
text(pca$x[,1], pca$x[,2], colnames(x), col = mycols)
```
Scree Plot
```{r}
pca.var2 <- round((pca$sdev^2)/sum(pca$sdev^2) * 100)
pca.var2
barplot(pca.var2, xlab = "Principal Component", ylab = "Percent Variation")
```

```{r}
## Lets focus on PC1 as it accounts for > 90% of variance 
par(mar=c(10, 3, 0.35, 0))
barplot(pca$rotation[,1], las=2)
```
```{r}
## Lets focus on PC1 as it accounts for > 90% of variance 
par(mar=c(10, 3, 0.35, 0))
barplot(pca$rotation[,2], las=2)
```

